/**
 * generate-seed.ts — Import mock data and output SQL inserts for Supabase.
 *
 * Maps names/labels in mock data → IDs required by DB FK constraints.
 * Output: supabase/seed.sql
 *
 * Run: npx tsx scripts/generate-seed.ts
 */

import { writeFileSync } from "fs";
import { resolve } from "path";

import {
  MOCK_DOUBLES_PLAYERS,
  MOCK_PAIRS,
  MOCK_DOUBLES_GROUPS,
  MOCK_DOUBLES_MATCHES,
  MOCK_DOUBLES_KO,
  MOCK_TEAM_PLAYERS,
  MOCK_TEAMS,
  MOCK_TEAM_GROUPS,
  MOCK_TEAM_MATCHES,
  MOCK_TEAM_KO,
} from "../src/app/admin/_mock";

// ── Helpers ──

/** Escape single quotes for SQL strings */
const esc = (s: string) => s.replace(/'/g, "''");

/** SQL string literal or null */
const str = (v: string | undefined | null): string =>
  v == null ? "null" : `'${esc(v)}'`;

/** SQL text[] literal */
const textArr = (arr: string[]): string =>
  arr.length === 0
    ? "'{}'::text[]"
    : `array[${arr.map((v) => `'${esc(v)}'`).join(",")}]::text[]`;

/** SQL jsonb literal */
const jsonb = (v: unknown): string =>
  `'${esc(JSON.stringify(v))}'::jsonb`;

/** SQL int or null */
const num = (v: number | undefined | null): string =>
  v == null ? "null" : String(v);

// ── Build lookup maps ──

// 1. doubles player name → id
const doublesPlayerNameToId = new Map<string, string>();
for (const p of MOCK_DOUBLES_PLAYERS) {
  doublesPlayerNameToId.set(p.name, p.id);
}

// 2. pair label ("name1 – name2") → pair id
const pairLabelToId = new Map<string, string>();
for (const pair of MOCK_PAIRS) {
  const label = `${pair.p1} – ${pair.p2}`;
  pairLabelToId.set(label, pair.id);
}

// 3. team member resolution: since names like "Quân", "Phương" appear in
//    multiple teams, we build a per-team mapping. MOCK_TEAM_PLAYERS is
//    generated by iterating TEAM_LIST → members in order, so we can rebuild
//    the same mapping.
const teamMemberToPlayerId = new Map<string, string>(); // key: "teamId:memberName"
{
  let idx = 1;
  // Re-derive from MOCK_TEAMS and MOCK_TEAM_PLAYERS in the same order
  // MOCK_TEAM_PLAYERS is built: for each team in TEAM_LIST order, for each member
  for (const team of MOCK_TEAMS) {
    for (const memberName of team.members) {
      const playerId = `t${String(idx).padStart(2, "0")}`;
      teamMemberToPlayerId.set(`${team.id}:${memberName}`, playerId);
      idx++;
    }
  }
}

// 4. team name → team id
const teamNameToId = new Map<string, string>();
for (const t of MOCK_TEAMS) {
  teamNameToId.set(t.name, t.id);
}

// ── Generate SQL ──

const lines: string[] = [];
lines.push("-- Auto-generated seed data. Do not edit by hand.");
lines.push("-- Generated: " + new Date().toISOString());
lines.push("");

// doubles_players
lines.push("-- doubles_players");
for (const p of MOCK_DOUBLES_PLAYERS) {
  lines.push(
    `INSERT INTO doubles_players (id, name, phone, gender, club) VALUES (${str(p.id)}, ${str(p.name)}, ${str(p.phone)}, ${str(p.gender)}, ${str(p.club)}) ON CONFLICT (id) DO NOTHING;`
  );
}
lines.push("");

// doubles_pairs — map p1/p2 names → player IDs
lines.push("-- doubles_pairs");
for (const pair of MOCK_PAIRS) {
  const p1Id = doublesPlayerNameToId.get(pair.p1);
  const p2Id = doublesPlayerNameToId.get(pair.p2);
  if (!p1Id || !p2Id) {
    throw new Error(`Cannot resolve doubles pair player: p1="${pair.p1}" p2="${pair.p2}"`);
  }
  lines.push(
    `INSERT INTO doubles_pairs (id, p1, p2) VALUES (${str(pair.id)}, ${str(p1Id)}, ${str(p2Id)}) ON CONFLICT (id) DO NOTHING;`
  );
}
lines.push("");

// doubles_groups — map entry labels → pair IDs
lines.push("-- doubles_groups");
for (const g of MOCK_DOUBLES_GROUPS) {
  const entryIds = g.entries.map((label) => {
    const pairId = pairLabelToId.get(label);
    if (!pairId) throw new Error(`Cannot resolve pair label: "${label}"`);
    return pairId;
  });
  lines.push(
    `INSERT INTO doubles_groups (id, name, entries) VALUES (${str(g.id)}, ${str(g.name)}, ${textArr(entryIds)}) ON CONFLICT (id) DO NOTHING;`
  );
}
lines.push("");

// doubles_matches — map pairA/pairB labels → pair IDs
lines.push("-- doubles_matches");
for (const m of MOCK_DOUBLES_MATCHES) {
  const pairAId = pairLabelToId.get(m.pairA);
  const pairBId = pairLabelToId.get(m.pairB);
  if (!pairAId || !pairBId) {
    throw new Error(`Cannot resolve doubles match pairs: "${m.pairA}" / "${m.pairB}"`);
  }
  lines.push(
    `INSERT INTO doubles_matches (id, group_id, pair_a, pair_b, "table", best_of, sets, status, winner, sets_a, sets_b) VALUES (${str(m.id)}, ${str(m.groupId)}, ${str(pairAId)}, ${str(pairBId)}, ${num(m.table)}, ${num(m.bestOf)}, ${jsonb(m.sets)}, ${str(m.status)}, null, 0, 0) ON CONFLICT (id) DO NOTHING;`
  );
}
lines.push("");

// doubles_ko — bracket progression: qf→sf→f
lines.push("-- doubles_ko");
const doublesKoBracket: Record<string, { next_match_id: string | null; next_slot: string | null }> = {
  "dko-qf1": { next_match_id: "dko-sf1", next_slot: "a" },
  "dko-qf2": { next_match_id: "dko-sf1", next_slot: "b" },
  "dko-qf3": { next_match_id: "dko-sf2", next_slot: "a" },
  "dko-qf4": { next_match_id: "dko-sf2", next_slot: "b" },
  "dko-sf1": { next_match_id: "dko-f", next_slot: "a" },
  "dko-sf2": { next_match_id: "dko-f", next_slot: "b" },
  "dko-f":   { next_match_id: null, next_slot: null },
};

// Insert in reverse order (f → sf → qf) so FK next_match_id references exist
const doublesKoReversed = [...MOCK_DOUBLES_KO].reverse();
for (const m of doublesKoReversed) {
  const bracket = doublesKoBracket[m.id] ?? { next_match_id: null, next_slot: null };
  lines.push(
    `INSERT INTO doubles_ko (id, round, best_of, label_a, label_b, entry_a, entry_b, sets, status, winner, sets_a, sets_b, next_match_id, next_slot) VALUES (${str(m.id)}, ${str(m.round)}, ${num(m.bestOf)}, ${str(m.labelA)}, ${str(m.labelB)}, null, null, ${jsonb(m.sets)}, ${str(m.status)}, null, 0, 0, ${str(bracket.next_match_id)}, ${str(bracket.next_slot)}) ON CONFLICT (id) DO NOTHING;`
  );
}
lines.push("");

// team_players
lines.push("-- team_players");
for (const p of MOCK_TEAM_PLAYERS) {
  lines.push(
    `INSERT INTO team_players (id, name, phone, gender, club) VALUES (${str(p.id)}, ${str(p.name)}, ${str(p.phone)}, ${str(p.gender)}, ${str(p.club)}) ON CONFLICT (id) DO NOTHING;`
  );
}
lines.push("");

// teams — map member names → team_player IDs (per-team to handle duplicate names)
lines.push("-- teams");
for (const t of MOCK_TEAMS) {
  const memberIds = t.members.map((name) => {
    const id = teamMemberToPlayerId.get(`${t.id}:${name}`);
    if (!id) throw new Error(`Cannot resolve team player name: "${name}" in team "${t.id}"`);
    return id;
  });
  lines.push(
    `INSERT INTO teams (id, name, members) VALUES (${str(t.id)}, ${str(t.name)}, ${textArr(memberIds)}) ON CONFLICT (id) DO NOTHING;`
  );
}
lines.push("");

// team_groups — map team names → team IDs
lines.push("-- team_groups");
for (const g of MOCK_TEAM_GROUPS) {
  const entryIds = g.entries.map((name) => {
    const teamId = teamNameToId.get(name);
    if (!teamId) throw new Error(`Cannot resolve team name: "${name}"`);
    return teamId;
  });
  lines.push(
    `INSERT INTO team_groups (id, name, entries) VALUES (${str(g.id)}, ${str(g.name)}, ${textArr(entryIds)}) ON CONFLICT (id) DO NOTHING;`
  );
}
lines.push("");

// team_matches — map teamA/teamB names → team IDs
lines.push("-- team_matches");
for (const m of MOCK_TEAM_MATCHES) {
  const teamAId = teamNameToId.get(m.teamA);
  const teamBId = teamNameToId.get(m.teamB);
  if (!teamAId || !teamBId) {
    throw new Error(`Cannot resolve team match teams: "${m.teamA}" / "${m.teamB}"`);
  }
  lines.push(
    `INSERT INTO team_matches (id, group_id, team_a, team_b, "table", status, score_a, score_b, winner, individual) VALUES (${str(m.id)}, ${str(m.groupId)}, ${str(teamAId)}, ${str(teamBId)}, ${num(m.table)}, ${str(m.status)}, 0, 0, null, ${jsonb(m.individual)}) ON CONFLICT (id) DO NOTHING;`
  );
}
lines.push("");

// team_ko — bracket progression: sf→f
lines.push("-- team_ko");
const teamKoBracket: Record<string, { next_match_id: string | null; next_slot: string | null }> = {
  "tko-sf1": { next_match_id: "tko-f", next_slot: "a" },
  "tko-sf2": { next_match_id: "tko-f", next_slot: "b" },
  "tko-f":   { next_match_id: null, next_slot: null },
};

// Insert in reverse order (f → sf) so FK next_match_id references exist
const teamKoReversed = [...MOCK_TEAM_KO].reverse();
for (const m of teamKoReversed) {
  const bracket = teamKoBracket[m.id] ?? { next_match_id: null, next_slot: null };
  lines.push(
    `INSERT INTO team_ko (id, round, label_a, label_b, entry_a, entry_b, status, score_a, score_b, winner, individual, lineup, next_match_id, next_slot) VALUES (${str(m.id)}, ${str(m.round)}, ${str(m.labelA)}, ${str(m.labelB)}, null, null, ${str(m.status)}, 0, 0, null, ${jsonb(m.individual ?? [])}, null, ${str(bracket.next_match_id)}, ${str(bracket.next_slot)}) ON CONFLICT (id) DO NOTHING;`
  );
}
lines.push("");

// ── Write output ──
const outPath = resolve(__dirname, "../supabase/seed.sql");
writeFileSync(outPath, lines.join("\n"), "utf8");
console.log(`Seed SQL written to ${outPath} (${lines.length} lines)`);
